sudo: required
services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}

before_install:
  - docker build -t mfarix/fibonacci-calculator-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mfarix/fibonacci-calculator-react-test npm run test -- --coverage

after_success:
  - export REPO=$DOCKER_USERNAME/fibonacci-calculator
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $REPO:$TAG:$COMMIT
  - docker build -t $REPO-client:$COMMIT -t $REPO-client:$TAG ./client
  - docker build -t $REPO-server:$COMMIT -t $REPO-server:$TAG ./server
  - docker build -t $REPO-worker:$COMMIT -t $REPO-worker:$TAG ./worker
  - docker build -t $REPO-nginx:$COMMIT -t $REPO-nginx:$TAG ./nginx
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push images to Docker Hub
  - docker push $REPO-client
  - docker push $REPO-server
  - docker push $REPO-worker
  - docker push $REPO-nginx
  # Replace the <TAG> with the real version number
  - sed -i='' "s/<TAG>/$COMMIT/" Dockerrun.aws.json

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: fibonacci-calculator
  env: FibonacciCalculator
  bucket_name: "elasticbeanstalk-ap-southeast-1-512200996832"
  bucket_path: "fibonacci-calculator"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
